import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "../components/ui/sonner";

const salmondFont = localFont({
  src: "../public/font/salmond.woff",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={salmondFont.className}>
      <body className={`antialiased`}>
        <main>{children}</main>
        <Toaster
          toastOptions={{
            style: {
              background: "#1E293B",
              color: "#F4C00C",
            },
          }}
        />
      </body>
    </html>
  );
}
