export type Course = {
  id: string;
  name: string;
  sport: string[];
  level: string;
  date: Date;
  timeFrom: string;
  timeTo: string;
  trainers: string[];
  room: string;
  description: string;
  maxParticipants: number;
  price: number;
  isStandingOrder: boolean;
  frequency: string | null;
  weekdays: string[];
  weekdayTimings: Record<string, { timeFrom: string; timeTo: string }> | null;
  endDate: Date | null;
  parentCourseId: string | null;
  status: string;
  createdBy: string;
  businessId: string | null;
  coverImage: string | null;
  createdAt: Date;
  updatedAt: Date;
};
